### ISSUE TITLE
Installation fails on Macbook

### ISSUE THREAD

**Issue by kamakshidasan** [Hrily/TopMusicPull#17]
259 INFO: PyInstaller: 3.2
259 INFO: Python: 2.7.12
348 INFO: Platform: Darwin-16.1.0-x86_64-i386-64bit
350 INFO: wrote /Users/stuti/Downloads/TopMusicPull-master/music_crawler.spec
410 INFO: UPX is not available.
412 INFO: Extending PYTHONPATH with paths
['/Users/stuti/Downloads/TopMusicPull-master',
 '/Users/stuti/Downloads/TopMusicPull-master']
412 INFO: checking Analysis
453 INFO: checking PYZ
474 INFO: checking PKG
483 INFO: Bootloader /usr/local/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
483 INFO: checking EXE
498 INFO: Building because name changed
498 INFO: Building EXE from out00-EXE.toc
498 INFO: Appending archive to EXE /Users/stuti/Downloads/TopMusicPull-master/dist/music_crawler
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/api.py", line 568, in assemble
    with open(self.name, 'wb') as outf:
IOError: [Errno 21] Is a directory: '/Users/stuti/Downloads/TopMusicPull-master/dist/music_crawler'

**Comment by kamakshidasan** [comment]
Edit: The same error props up on my Ubuntu machine as well.

**Comment by Hrily** [comment]
@salman-bhai 

> IOError: [Errno 21] Is a directory: '/Users/stuti/Downloads/TopMusicPull-master/dist/music_crawler'

dist/music_crawler is a directory
we need to install dist/music_crawler/music_crawler 

Please make the changes accordingly

@kamakshidasan 
Thank you for pointing out the Issue... :)

**Comment by sbshah97** [comment]
Changes made @kamakshidasan Thank you for pointing that out!
Kindly pull `master` and changes will have been done!
